databases:
  - name: labelleteranga-db
    plan: free
    databaseName: labelleteranga
    user: labelleteranga

services:
  - type: web
    name: labelleteranga-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_superuser_if_missing"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "api.labelleteranga.com,.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://frontend-umber-ten-209ve5rkqa.vercel.app,https://labelleteranga.com,https://www.labelleteranga.com"
      - key: FRONTEND_URL
        value: "https://frontend-umber-ten-209ve5rkqa.vercel.app"
      - key: BACKEND_URL
        value: "https://labelleteranga-api.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: labelleteranga-db
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_CURRENCY
        value: "xof"
      - key: WAVE_API_KEY
        sync: false
      - key: ORANGE_MONEY_CLIENT_ID
        sync: false
      - key: ORANGE_MONEY_CLIENT_SECRET
        sync: false
      - key: ORANGE_MONEY_MERCHANT_KEY
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_TEMPLATE_NAME
        sync: false
      - key: WHATSAPP_SHOP_NUMBER
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
