# Generated by Django 5.0.7 on 2026-09-18 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('stores', '0006_pointofsale_description_pointofsale_online_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='stores.pointofsale'),
        ),
    ]
