# Generated by Django 5.0.7 on 2026-09-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orange_money_order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte bancaire (Stripe)'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('cash', 'Especes a la livraison')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='wave_checkout_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
