# Generated by Django 5.0.7 on 2026-09-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_latitude_order_delivery_longitude_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, help_text='Magasin ayant traite la commande (optionnel, pour la cloture de caisse par magasin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.pointofsale'),
        ),
    ]
