# Generated by Django 5.0.7 on 2026-09-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cashier_order_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_mode',
            field=models.CharField(choices=[('direct', 'Vente directe'), ('dine_in', 'Sur place')], default='direct', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='table_label',
            field=models.CharField(blank=True, max_length=40, verbose_name='Table'),
        ),
    ]
