# Generated by Django 5.0.7 on 2026-09-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_service_mode_order_table_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment',
            field=models.CharField(choices=[('delivery', 'Livraison'), ('pickup', 'A emporter')], default='delivery', max_length=10),
        ),
    ]
