# Generated by Django 5.0.7 on 2026-09-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_void_reason_order_voided_at_order_voided_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whatsapp_error',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
