# Generated by Django 5.0.7 on 2026-09-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_whatsapp_error_order_whatsapp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
