# Generated by Django 5.2.15 on 2026-09-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_declared_at_order_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise fidelite'),
        ),
        migrations.AddField(
            model_name='order',
            name='reward_label',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
