# Generated by Django 5.2.15 on 2026-09-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_discount_amount_order_reward_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pourboire'),
        ),
    ]
