# Generated by Django 5.2.15 on 2026-09-21 20:27

from django.db import migrations, models


def mark_existing_handled(apps, schema_editor):
    """Les commandes deja recues avant cette fonction sont considerees comme traitees : seules les nouvelles declenchent l'alerte."""
    from django.utils import timezone

    apps.get_model("orders", "Order").objects.filter(handled_at__isnull=True).update(handled_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_customer_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Commande finalisee a la caisse'),
        ),
        migrations.RunPython(mark_existing_handled, migrations.RunPython.noop),
    ]
