# Generated by Django 5.2.15 on 2026-09-21 20:55

from django.db import migrations, models


def mark_existing_received(apps, schema_editor):
    """Les commandes deja recues avant cette fonction sont considerees comme confirmees : seules les nouvelles font sonner l'alerte."""
    from django.utils import timezone

    apps.get_model("orders", "Order").objects.filter(received_at__isnull=True).update(received_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_commande_finalisee_caisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reception confirmee a la caisse'),
        ),
        migrations.RunPython(mark_existing_received, migrations.RunPython.noop),
    ]
