# Generated by Django 5.2.15 on 2026-09-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_commande_reception_confirmee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ack_whatsapp_error',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='ack_whatsapp_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
