# Generated by Django 5.2.15 on 2026-09-24 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_payment_method_change_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_action',
            field=models.CharField(blank=True, choices=[('void', 'Annulation'), ('change_payment', 'Correction de paiement')], max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pending_payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Carte bancaire (Stripe)'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('cash', 'Especes a la livraison')], max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pending_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='pending_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pending_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
