# Generated by Django 5.0.7 (ecrite a la main : voir apps/payments/orange_money.py et
# apps/payments/views.py:orange_money_webhook pour l'usage de ce champ)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_pending_action_order_pending_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orange_money_webhook_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
