# Generated by Django 5.0.7 on 2026-09-18 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_stock_quantity'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('discount_type', models.CharField(choices=[('percent', 'Pourcentage'), ('fixed', 'Montant fixe (FCFA)')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Ex: 10 pour -10%% ou 500 pour -500 FCFA', max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='catalog.category')),
                ('point_of_sale', models.ForeignKey(blank=True, help_text='Laisser vide pour une promotion valable partout (y compris en ligne).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='stores.pointofsale')),
                ('products', models.ManyToManyField(blank=True, help_text='Laisser vide pour appliquer a toute la categorie / tout le catalogue.', related_name='promotions', to='catalog.product')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
