# Generated by Django 5.0.7 on 2026-10-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_poulet_entier_resto_grillades'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_zone',
            field=models.JSONField(blank=True, null=True, verbose_name='Zone du prix sur la photo'),
        ),
    ]
