# Generated by Django 5.0.7 on 2026-10-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_zones_prix_affiches_resto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_by_weight',
            field=models.BooleanField(default=False, verbose_name='Vendu au poids (prix au kg)'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='Format')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix (XOF)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
