# Generated by Django 5.2.15 on 2026-09-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminsecuritycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsecuritycode',
            name='secondary_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminsecuritycode',
            name='secondary_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminsecuritycode',
            name='secondary_pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
