# Generated by Django 5.0.7 on 2026-09-18 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_wave', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_orange_money', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('declared_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('declared_wave', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('declared_orange_money', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('declared_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_closings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
