# Generated by Django 5.0.7 on 2026-09-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, help_text='Vide = commandes en ligne non affectees a un magasin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings', to='stores.pointofsale'),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyclosing',
            unique_together={('date', 'point_of_sale')},
        ),
    ]
