# Generated by Django 5.0.7 on 2026-09-18 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyclosing_point_of_sale_alter_dailyclosing_date_and_more'),
        ('stores', '0002_seed_real_points_of_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyclosing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='cashier',
            field=models.ForeignKey(blank=True, help_text="Renseigne pour la fermeture de caisse d'un caissier ; vide pour la cloture globale d'un point de vente.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_closings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyclosing',
            unique_together={('date', 'point_of_sale', 'cashier')},
        ),
    ]
