# Generated by Django 5.0.7 on 2026-09-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_dailyclosing_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='initial_discrepancy_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
