# Generated by Django 5.2.15 on 2026-09-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_dailyclosing_initial_discrepancy_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='auto_closed',
            field=models.BooleanField(default=False, verbose_name='Fermeture automatique (caisse non fermee par le caissier)'),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='covers_from',
            field=models.DateField(blank=True, null=True, verbose_name='Solde reporte depuis'),
        ),
    ]
