# Generated by Django 5.2.15 on 2026-09-23 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_fermeture_automatique_solde_reporte'),
        ('stores', '0035_bande_plats_senegalais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fond de caisse (especes)')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_openings', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openings_done', to=settings.AUTH_USER_MODEL)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_openings', to='stores.pointofsale')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'point_of_sale', 'cashier')},
            },
        ),
    ]
