# Generated by Django 5.2.15 on 2026-09-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_ouverture_de_caisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='tips_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pourboires (informatif)'),
        ),
    ]
