# Generated by Django 5.2.15 on 2026-09-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_dailyclosing_tips_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='covers_through',
            field=models.DateField(blank=True, null=True, verbose_name="Regroupe jusqu'au"),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='covers_from',
            field=models.DateField(blank=True, null=True, verbose_name='Solde reporte depuis (ancien)'),
        ),
    ]
