# Generated by Django 5.0.7 on 2026-09-18 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_promotion'),
        ('stores', '0002_seed_real_points_of_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'En cours'), ('validated', 'Valide'), ('cancelled', 'Annule')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='stores.pointofsale')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('sale_pos', 'Vente en caisse'), ('invoice', 'Facture client'), ('invoice_cancel', 'Annulation de facture'), ('purchase_receipt', 'Reception fournisseur'), ('manual', 'Correction manuelle'), ('inventory', "Ajustement d'inventaire"), ('import', 'Import Excel')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='stores.pointofsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretical_quantity', models.IntegerField()),
                ('counted_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stores.inventorycount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
            ],
            options={
                'ordering': ['product__name'],
                'unique_together': {('count', 'product')},
            },
        ),
    ]
