# Generated by Django 5.0.7 on 2026-09-18 22:14

import apps.stores.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_restaurant_categories'),
        ('stores', '0003_inventorycount_stockmovement_inventorycountline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawerOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawer_openings', to='stores.pointofsale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Africa/Dakar', max_length=60, verbose_name='Fuseau horaire')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('legal_form', models.CharField(blank=True, max_length=60, verbose_name='Forme juridique')),
                ('share_capital', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Capital social')),
                ('ninea', models.CharField(blank=True, max_length=60, verbose_name='NINEA')),
                ('rccm', models.CharField(blank=True, max_length=60, verbose_name='RCCM')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='TVA (%)')),
                ('prices_include_vat', models.BooleanField(default=True, verbose_name='Prix TTC')),
                ('payment_methods', models.JSONField(default=apps.stores.models.default_payment_methods, verbose_name='Moyens de paiement acceptes')),
                ('receipt_slogan', models.CharField(blank=True, default="L'art du service", max_length=120)),
                ('receipt_footer', models.CharField(blank=True, default='Merci de votre visite !', max_length=200)),
                ('module_hold', models.BooleanField(default=True, verbose_name='Ventes en attente')),
                ('module_history', models.BooleanField(default=True, verbose_name='Historique du jour')),
                ('module_qr', models.BooleanField(default=True, verbose_name='QR Wave / Orange Money')),
                ('module_dine_in', models.BooleanField(default=True, verbose_name='Vente sur place (tables)')),
                ('module_customer_orders', models.BooleanField(default=True, verbose_name='Commandes client')),
                ('module_drawer', models.BooleanField(default=True, verbose_name='Tiroir-caisse')),
                ('module_xreport', models.BooleanField(default=True, verbose_name='Rapport X')),
                ('point_of_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.pointofsale')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_links', to='catalog.category')),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='stores.pointofsale')),
            ],
            options={
                'ordering': ['order', 'category__name'],
                'unique_together': {('point_of_sale', 'category')},
            },
        ),
    ]
