# Generated by Django 5.0.7 on 2026-09-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_seed_store_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsale',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='online_enabled',
            field=models.BooleanField(default=False, verbose_name='Site web en ligne'),
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='Identifiant du site'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('sale_pos', 'Vente en caisse'), ('invoice', 'Facture client'), ('invoice_cancel', 'Annulation de facture'), ('purchase_receipt', 'Reception fournisseur'), ('online_order', 'Commande en ligne'), ('manual', 'Correction manuelle'), ('inventory', "Ajustement d'inventaire"), ('import', 'Import Excel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='email',
            field=models.EmailField(blank=True, default='info@labelleteranga.com', max_length=254),
        ),
    ]
