# Generated by Django 5.0.7 on 2026-09-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_seed_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('sale_pos', 'Vente en caisse'), ('invoice', 'Facture client'), ('invoice_cancel', 'Annulation de facture'), ('purchase_receipt', 'Reception fournisseur'), ('online_order', 'Commande en ligne'), ('sale_void', 'Vente annulee'), ('manual', 'Correction manuelle'), ('inventory', "Ajustement d'inventaire"), ('import', 'Import Excel')], max_length=20),
        ),
    ]
