# Generated by Django 5.0.7 on 2026-09-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_stockmovement_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='track_stock',
            field=models.BooleanField(default=True, verbose_name='Suivi du stock'),
        ),
    ]
