# Generated by Django 5.0.7 on 2026-09-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_resto_no_stock_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='orange_pay_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='Lien de paiement Orange Money / Max it'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='wave_pay_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='Lien de paiement Wave'),
        ),
    ]
