# Generated by Django 5.0.7 on 2026-09-19 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_restaurant_categories'),
        ('stores', '0012_seed_pay_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='orange_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numero marchand Orange Money'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='wave_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numero marchand Wave'),
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('lunch', 'Menu du midi'), ('special', 'Speciaux du jour')], default='lunch', max_length=10)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='Horaires / remarque')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='stores.pointofsale')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('point_of_sale', 'date', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Numero de choix')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix special')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.dailymenu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('menu', 'number'), ('menu', 'product')},
            },
        ),
    ]
