# Generated by Django 5.2.15 on 2026-09-19 04:25

import apps.stores.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_storesettings_orange_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='loyalty_enabled',
            field=models.BooleanField(default=False, verbose_name='Fidelite active'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='loyalty_min_order',
            field=models.PositiveIntegerField(default=0, verbose_name="Montant minimum d'une commande comptee (FCFA)"),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='loyalty_mode',
            field=models.CharField(choices=[('orders', 'Nombre de commandes'), ('amount', 'Montant cumule')], default='orders', max_length=10, verbose_name='Critere'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='loyalty_reward_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Texte de la recompense'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='loyalty_reward_type',
            field=models.CharField(choices=[('percent', 'Reduction en %'), ('amount', 'Reduction en FCFA'), ('gift', 'Cadeau offert')], default='percent', max_length=10, verbose_name='Type de recompense'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='loyalty_reward_value',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=10, verbose_name='Valeur (% ou FCFA)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='loyalty_threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='Seuil (commandes ou FCFA)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='loyalty_valid_days',
            field=models.PositiveIntegerField(default=60, verbose_name='Validite de la recompense (jours)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Reseaux sociaux'),
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('occasion', models.CharField(blank=True, max_length=80, verbose_name='Occasion')),
                ('description', models.TextField(blank=True)),
                ('includes', models.TextField(blank=True, verbose_name='Contenu (une ligne par element)')),
                ('serves', models.CharField(blank=True, max_length=60, verbose_name='Pour combien de personnes')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('image', models.ImageField(blank=True, upload_to='combos/')),
                ('weekend_only', models.BooleanField(default=False, verbose_name='Uniquement le week-end')),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('min_notice_hours', models.PositiveIntegerField(default=24, verbose_name='Delai de reservation (heures)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='stores.pointofsale')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComboRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_name', models.CharField(max_length=120)),
                ('combo_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=30)),
                ('event_date', models.DateField()),
                ('guests', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('confirmed', 'Confirmee'), ('cancelled', 'Annulee')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='stores.combo')),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_requests', to='stores.pointofsale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Progression vers la prochaine recompense')),
                ('rewards_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_members', to='stores.pointofsale')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('point_of_sale', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.stores.models._reward_code, max_length=8, unique=True)),
                ('reward_type', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('label', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_on_order', models.CharField(blank=True, max_length=40)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='stores.loyaltymember')),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rewards', to='stores.pointofsale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(blank=True, db_index=True, max_length=40)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('service_rating', models.PositiveSmallIntegerField()),
                ('quality_rating', models.PositiveSmallIntegerField()),
                ('q_speed', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rapidite du service')),
                ('q_welcome', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Accueil et amabilite')),
                ('q_recommend', models.CharField(blank=True, max_length=10, verbose_name='Recommanderait')),
                ('dish', models.CharField(blank=True, max_length=150, verbose_name='Plat / produit concerne')),
                ('comment', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('reply', models.TextField(blank=True, verbose_name='Reponse du commerce')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.pointofsale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
