# Generated by Django 5.2.15 on 2026-09-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_no_stock_tracking_resto_forage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_hidden',
            field=models.BooleanField(default=False, verbose_name='Commentaire retire du site (la note reste comptee)'),
        ),
    ]
