# Generated by Django 5.2.15 on 2026-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_configure_ferme'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='track_stock',
            field=models.BooleanField(default=True, verbose_name='Suivre le stock de ce produit'),
        ),
    ]
