# Generated by Django 5.2.15 on 2026-09-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_suivi_stock_par_produit_resto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Afficher sur les documents')),
                ('stamp_png', models.BinaryField(blank=True, null=True, verbose_name='Cachet')),
                ('signature_png', models.BinaryField(blank=True, null=True, verbose_name='Signature')),
                ('signer_name', models.CharField(blank=True, max_length=120, verbose_name='Nom du signataire')),
                ('signer_title', models.CharField(blank=True, max_length=120, verbose_name='Fonction')),
                ('place', models.CharField(blank=True, max_length=80, verbose_name='Ville')),
                ('certified_text', models.CharField(default='Certifié conforme', max_length=80, verbose_name='Mention')),
                ('show_date', models.BooleanField(default=True, verbose_name='Date du jour')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
