# Generated by Django 5.2.15 on 2026-09-19 21:05

from django.db import migrations, models


def tint_existing(apps, schema_editor):
    """Le cachet deja enregistre est conserve comme source : sa couleur pourra etre changee sans le renvoyer."""
    CompanySeal = apps.get_model("stores", "CompanySeal")
    for seal in CompanySeal.objects.exclude(stamp_png=None):
        seal.stamp_source = seal.stamp_png
        seal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_company_seal'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyseal',
            name='stamp_color',
            field=models.CharField(default='original', max_length=12, verbose_name='Couleur du cachet'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='stamp_source',
            field=models.BinaryField(blank=True, null=True, verbose_name="Cachet (couleurs d'origine)"),
        ),
        migrations.RunPython(tint_existing, migrations.RunPython.noop),
    ]
