# Generated by Django 5.2.15 on 2026-09-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0024_cachet_couleur_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyseal',
            name='legal_line',
            field=models.CharField(blank=True, default='RCCM SN ZGR 2023 A 2946 · NINEA 010903103 1P1', max_length=160, verbose_name='Identifiants légaux (RCCM, NINEA)'),
        ),
    ]
