# Generated by Django 5.2.15 on 2026-09-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_cachet_identifiants_legaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyseal',
            name='contact_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse (pied de page)'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=60, verbose_name='Téléphone (pied de page)'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=60, verbose_name='WhatsApp (pied de page)'),
        ),
    ]
