# Generated by Django 5.2.15 on 2026-09-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0026_cachet_coordonnees_pied_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyseal',
            name='contact_email',
            field=models.CharField(blank=True, max_length=120, verbose_name='Courriel (vide = courriel par défaut)'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='contact_extra',
            field=models.TextField(blank=True, max_length=500, verbose_name='Lignes supplémentaires (une par ligne)'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='contact_website',
            field=models.CharField(blank=True, max_length=120, verbose_name='Site web'),
        ),
    ]
