# Generated by Django 5.2.15 on 2026-09-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0027_cachet_infos_supplementaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyseal',
            name='show_certified',
            field=models.BooleanField(default=True, verbose_name='Mention « Document certifié »'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='show_signature',
            field=models.BooleanField(default=True, verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='show_stamp',
            field=models.BooleanField(default=True, verbose_name='Cachet'),
        ),
    ]
