# Generated by Django 5.2.15 on 2026-09-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0029_combos_resto'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='display_name',
            field=models.CharField(blank=True, max_length=120, verbose_name="Nom affiché dans ce point de vente (vide = nom d'origine)"),
        ),
    ]
