# Generated by Django 5.2.15 on 2026-09-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_classer_produits'),
        ('stores', '0032_prix_combos_sur_produits'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titre')),
                ('text', models.TextField(blank=True, verbose_name='Texte')),
                ('show_prices', models.BooleanField(default=True, verbose_name='Afficher les prix')),
                ('include_combos', models.BooleanField(default=False, verbose_name='Ajouter automatiquement les combos actifs')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category', verbose_name='Categorie (produits ajoutes automatiquement)')),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='stores.pointofsale')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromoBandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=80, verbose_name='Sous-titre')),
                ('order', models.PositiveIntegerField(default=0)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.promoband')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
