# Generated by Django 5.2.15 on 2026-09-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0035_bande_plats_senegalais'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='module_daily_menu',
            field=models.BooleanField(default=True, verbose_name='Menu du jour'),
        ),
    ]
