# Generated by Django 5.2.15 on 2026-09-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0049_taille_police_uniforme_produits'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='La Belle Teranga (LATERANGA)', max_length=150, verbose_name="Nom de l'entreprise")),
                ('logo_png', models.BinaryField(blank=True, null=True, verbose_name='Logo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
