# Generated by Django 5.0.7 on 2026-10-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_sold_by_weight_productvariant'),
        ('stores', '0050_companybranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productvariant'),
        ),
        migrations.CreateModel(
            name='VariantStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_stocks', to='stores.pointofsale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.productvariant')),
            ],
            options={
                'unique_together': {('variant', 'point_of_sale')},
            },
        ),
    ]
