# Generated by Django 5.0.7 on 2026-10-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0052_produits_supermarche_ziguinchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix dans ce magasin'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='price_markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Supplement sur les prix (%)'),
        ),
        migrations.AddField(
            model_name='variantstock',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix de ce format dans ce magasin'),
        ),
    ]
