# Generated by Django 5.2.15 on 2026-10-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0054_supplement_ziguinchor_15'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='price_markup_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Supplement fixe sur les prix (FCFA)'),
        ),
    ]
