# Generated by Django 5.2.15 on 2026-10-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0056_supplement_fixe_ziguinchor_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
